trigger:
- master

pr:
- master

jobs:
  - job: x64
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        set -ex
        docker run -v $PWD:/t amd64/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make gcc; cd /t; CC=gcc make test"
    - script:
        sudo make clean
    - bash: |
        set -ex
        docker run -v $PWD:/t amd64/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make clang; cd /t; CC=clang make test"

  - job: arm64
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        set -ex
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t arm64v8/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make gcc; cd /t; CC=gcc make"
    - script:
        sudo make clean
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t arm64v8/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make clang; cd /t; CC=clang make"

  - job: armv7l
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        set -ex
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t arm32v7/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make gcc; cd /t; CC=gcc make"
    - script:
        sudo make clean
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t arm32v7/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make clang; cd /t; CC=clang make"

  - job: i386
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        set -ex
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t i386/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make gcc; cd /t; ARCH=x86 CC=gcc make test"
    - script:
        sudo make clean
    - bash: |
        set -ex
        docker run --rm -v $PWD:/t i386/debian:unstable-slim /bin/bash -c "set -ex; apt-get update; apt-get install -y libedit-dev nasm make clang; cd /t; ARCH=x86 CC=clang make test"
